### ISSUE TITLE
Improve setup by using cli and splitting up the wiki

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#1254]
**Is your feature request related to a problem? Please describe.**

The idea to improve build time for local development and even remote workflows is to split up the wiki into multiple parts and only run/build the parts you need. 

**Describe the solution you'd like**

For this we would like to use the cli. It could ask you which parts you want to run like `Identity`, `Get Started`, `Build` and so on. It should be possible to do that over a nice TUI and through flags like `iota-wiki start identity`
This would improve the local development experience.
Maybe we could even use this to detect in a PR which part of the Wiki changed to only run workflows on that part (might be a problem for broken links, so do we even want to do this?)

**Comment by Dr-Electron** [comment]
@jlvandenhout anything you would like to add?

**Comment by jlvandenhout** [comment]
Would be nice if we could select a subset of the Wiki, like build APIs and the SDK for example. For previews I guess we can do partial builds, but for test builds we still should do a full build because changes might affect other parts as well that reference the changed part. With regard to link checking, I'm not sure if I see the point in checking links on a partial built. As we probably want to do a full build in CI before merging anyway, I guess we do a full link check there.
