### ISSUE TITLE
Add more links to TIPs

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/iota-wiki#870]
**Describe the solution you'd like**

Our TIPs are a little bit hidden. 
A first step of improvement would be to add them to the `Develop` sidebar. Maybe before `Tutorials`? Or maybe even after `Protocol Overview`?

**Comment by lucas-tortora** [comment]
> **Describe the solution you'd like**
> 
> Our TIPs are a little bit hidden. A first step of improvement would be to add them to the `Develop` sidebar. Maybe before `Tutorials`? Or maybe even after `Protocol Overview`?

I think we could maybe make the `Protocol Overview` a doc instead of a link. This way, we could add a high-level overview of what's new in Stardust (tokenization, unlock conditions, etc.) with relevant links, how it compares with IOTA with a table or similar to list available features and a nice section about upcoming improvements to the protocol (TIPS). Ideally, we'd organize the TIPs in a sensible manner, for example, the most recently added at the top, followed by the ones that are in progress and, after that, rejected TIPs.

**Comment by Dr-Electron** [comment]
Yeah we need to get rid of the Introduction repo anyway. This docs should be part of the wiki. Makes it way more easy to integrate in the wiki than imo

On the other hand we may loose DRIs then. As it's now part of the Wiki 😅 

But yeah that's another topic.

> Ideally, we'd organize the TIPs in a sensible manner, for example, the most recently added at the top, followed by the ones that are in progress and, after that, rejected TIPs.

This is not too easy as we can't touch the TIPs repo too much.
But yeah we need more content about the TIPs in the now called Protocol Overview section

**Comment by Dr-Electron** [comment]
Ok. Should we still just add it to the sidebar for now? That would be an easy fix in the meantime we could even do today or tomorrow 🤔

**Comment by lucas-tortora** [comment]
> Ok. Should we still just add it to the sidebar for now? That would be an easy fix in the meantime we could even do today or tomorrow thinking

Definitely. Would you like to create the PR, and I review or the other way round?

**Comment by Dr-Electron** [comment]
Would be lovely if you could create the PR it. ❤️
